"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Badge,PageHeader} from "@/core/design-system";
type Row=Record<string,any>;
type Draft={id?:string;code:string;discountType:"percentage"|"fixed";discountValue:number;minOrderValue:number;maxUses:string;origin:string;active:boolean;expiresAt:string;productIds:string[];userIds:string[];productMode:"all"|"selected"|"categories"|"exclude";categoryIds:string[]};
const blank=():Draft=>({code:"CRZ10",discountType:"percentage",discountValue:10,minOrderValue:0,maxUses:"",origin:"admin",active:true,expiresAt:"",productIds:[],userIds:[],productMode:"all",categoryIds:[]});
const benefit=(c:Row)=>c.discount_type==="percentage"?Number(c.discount_value)+"%":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(c.discount_value||0));
const date=(v:string|null)=>!v?"Sem expiração":new Date(v).toLocaleDateString("pt-BR");
export function CouponManagerPage(){
 const [data,setData]=useState<any>(null),[state,setState]=useState<"loading"|"ready"|"error">("loading"),[selected,setSelected]=useState<Row|null>(null),[query,setQuery]=useState(""),[notice,setNotice]=useState(""),[draft,setDraft]=useState<Draft|null>(null),[customerQuery,setCustomerQuery]=useState(""),[customers,setCustomers]=useState<Row[]>([]),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch("/api/admin/coupons",{cache:"no-store"}),p=await r.json();if(!r.ok)throw new Error();setData(p);setState("ready")}catch{setState("error")}},[]);
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return(data?.coupons||[]).filter((c:Row)=>!q||c.code.toLowerCase().includes(q)||String(c.origin).toLowerCase().includes(q))},[data,query]);
 const openEditor=(row?:Row)=>setDraft(row?{id:row.id,code:row.code,discountType:row.discount_type,discountValue:Number(row.discount_value||0),minOrderValue:Number(row.min_order_value||0),maxUses:row.max_uses==null?"":String(row.max_uses),origin:row.origin||"admin",active:row.active!==false,expiresAt:row.expires_at?String(row.expires_at):"",productIds:[...(row.metadata?.scope_mode==="exclude"?row.metadata.excluded_product_ids||[]:row.product_ids||[])],userIds:(row.users||[]).map((u:Row)=>u.user_id),productMode:(row.metadata?.scope_mode==="categories"?"categories":row.metadata?.scope_mode==="exclude"?"exclude":row.metadata?.scope_mode==="selected"||(row.product_ids||[]).length?"selected":"all"),categoryIds:Array.isArray(row.metadata?.category_ids)?row.metadata.category_ids:[]}:blank());
 const save=async(next:Draft)=>{if(busy)return;setBusy(true);try{const r=await fetch("/api/admin/coupons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save_coupon",id:next.id,code:next.code.trim().toUpperCase(),discountType:next.discountType,discountValue:Number(next.discountValue),minOrderValue:Number(next.minOrderValue),maxUses:next.maxUses?Number(next.maxUses):null,active:next.active,expiresAt:next.expiresAt||null,origin:next.origin,productIds:next.productMode==="all"?[]:next.productIds,userIds:next.userIds,scopeMode:next.productMode,categoryIds:next.categoryIds})});const p=await r.json().catch(()=>({}));setNotice(r.ok?"Cupom salvo.":"Falha: "+(p.error||"COUPON_SAVE_FAILED"));if(r.ok){setDraft(null);setSelected(null);await load();}}catch{setNotice("Não foi possível salvar. Tente novamente.")}finally{setBusy(false)}};
 const searchCustomers=async()=>{const q=customerQuery.trim();if(!q)return setCustomers([]);const r=await fetch("/api/admin/customers?q="+encodeURIComponent(q)+"&limit=12",{cache:"no-store"});const p=await r.json().catch(()=>({}));setCustomers(r.ok?p.customers||[]:[])};
 if(state==="loading")return <main className="crz-couponmanager-state"><span className="crz-spinner"/><strong>Carregando cupons...</strong></main>;
 if(state==="error"||!data)return <main className="crz-couponmanager-state"><strong>Coupon Manager indisponível.</strong><button onClick={()=>void load()}>Tentar novamente</button></main>;
 const active=data.coupons.filter((c:Row)=>c.active&&(!c.expires_at||new Date(c.expires_at)>new Date())).length;
 return <main className="crz-couponmanager"><div className="crz-container">
  <PageHeader eyebrow="CRAZZY CLUB • CUPONS" title="Cupons e descontos" description="Crie descontos para todos, produtos específicos ou clientes encontrados por nome, e-mail ou Discord." actions={<button className="crz-button crz-button--primary crz-button--sm" onClick={()=>openEditor()}>+ Cupom</button>}/>
  <section className="crz-couponmanager-stats"><article><small>TOTAL</small><strong>{data.coupons.length}</strong></article><article><small>ATIVOS</small><strong>{active}</strong></article><article><small>USOS REAIS</small><strong>{data.coupons.reduce((s:number,c:Row)=>s+Number(c.real_uses||0),0)}</strong></article><article><small>RESTRITOS</small><strong>{data.coupons.filter((c:Row)=>c.product_ids.length||c.users.length).length}</strong></article></section>
  <section className="crz-couponmanager-toolbar"><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cupom..."/></label><a href="/painel/cupons">Carteira do cliente →</a></section>
  {notice&&<p className="crz-couponmanager-notice">{notice}</p>}
  {draft&&<section className="crz-couponmanager-detail" style={{marginBottom:12}}><header><div><small>CONFIGURAÇÃO</small><h2>{draft.id?"Editar cupom":"Novo cupom"}</h2></div><button onClick={()=>setDraft(null)}>×</button></header>
   <div className="crz-couponmanager-grid">
    <label><small>Código</small><input value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/></label>
    <label><small>Desconto</small><input type="number" min="0" value={draft.discountValue} onChange={e=>setDraft({...draft,discountValue:Number(e.target.value)})}/></label>
    <label><small>Tipo</small><select value={draft.discountType} onChange={e=>setDraft({...draft,discountType:e.target.value as Draft["discountType"]})}><option value="percentage">Porcentagem</option><option value="fixed">Valor fixo</option></select></label>
    <label><small>Pedido mínimo</small><input type="number" min="0" value={draft.minOrderValue} onChange={e=>setDraft({...draft,minOrderValue:Number(e.target.value)})}/></label>
    <label><small>Máximo de usos</small><input type="number" min="1" value={draft.maxUses} placeholder="Ilimitado" onChange={e=>setDraft({...draft,maxUses:e.target.value})}/></label>
    <label><small>Validade</small><input type="date" value={draft.expiresAt.slice(0,10)} onChange={e=>setDraft({...draft,expiresAt:e.target.value?e.target.value+"T23:59:59-03:00":""})}/></label><label><small>Disponível</small><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/></label>
    <label><small>Origem</small><select value={draft.origin} onChange={e=>setDraft({...draft,origin:e.target.value})}><option value="admin">Admin</option><option value="promotion">Promoção</option><option value="reward">Reward</option><option value="wheel">Roleta</option><option value="scratch">Raspadinha</option><option value="drop">Drop</option><option value="manual">Manual</option><option value="other">Outro</option></select></label>
   </div>
   <section className="crz-couponmanager-products"><strong>Aplicar em</strong><div>
    <button className={draft.productMode==="all"?"is-on":""} onClick={()=>setDraft({...draft,productMode:"all",productIds:[],categoryIds:[]})}>TODOS</button>
    <button className={draft.productMode==="selected"?"is-on":""} onClick={()=>setDraft({...draft,productMode:"selected",categoryIds:[]})}>PRODUTOS</button>
    <button className={draft.productMode==="categories"?"is-on":""} onClick={()=>setDraft({...draft,productMode:"categories",productIds:[]})}>CATEGORIAS</button>
    <button className={draft.productMode==="exclude"?"is-on":""} onClick={()=>setDraft({...draft,productMode:"exclude",categoryIds:[]})}>TODOS MENOS...</button>
   </div>
   {draft.productMode==="categories"&&<div>{(data.categories||[]).map((g:Row)=>{const on=draft.categoryIds.includes(g.id);return <button key={g.id} className={on?"is-on":""} onClick={()=>setDraft({...draft,categoryIds:on?draft.categoryIds.filter(id=>id!==g.id):[...draft.categoryIds,g.id]})}>{on?"✓ ":""}{g.name}</button>})}</div>}
   {(draft.productMode==="selected"||draft.productMode==="exclude")&&<div>{data.products.map((p:Row)=>{const on=draft.productIds.includes(p.id);return <button key={p.id} className={on?"is-on":""} onClick={()=>setDraft({...draft,productIds:on?draft.productIds.filter(id=>id!==p.id):[...draft.productIds,p.id]})}>{on?"✓ ":""}{p.name}</button>})}</div>}
   <small>{draft.productMode==="all"?"Catálogo inteiro participa.":draft.productMode==="selected"?"Só os produtos marcados participam.":draft.productMode==="categories"?"Todos os produtos das categorias marcadas participam.":"O cupom vale no catálogo inteiro, exceto os produtos marcados."}</small>
   </section>
   <section><strong>Clientes específicos</strong><div className="crz-couponmanager-toolbar"><label>⌕ <input value={customerQuery} onChange={e=>setCustomerQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void searchCustomers()}} placeholder="Nome, e-mail ou Discord..."/></label><button onClick={()=>void searchCustomers()}>Buscar</button></div>{customers.map((u:Row)=>{const on=draft.userIds.includes(u.user_id);return <button key={u.user_id} className="crz-button crz-button--secondary crz-button--sm" onClick={()=>setDraft({...draft,userIds:on?draft.userIds.filter(id=>id!==u.user_id):[...draft.userIds,u.user_id]})}>{on?"✓ ":""}{u.username||u.discord_global_name||u.discord_username||u.email||"Cliente"}</button>})}</section>
   <div className="crz-couponmanager-actions"><button className="crz-button crz-button--secondary crz-button--sm" onClick={()=>setDraft(null)}>Cancelar</button><button className="crz-button crz-button--primary crz-button--sm" disabled={busy} onClick={()=>void save(draft)}>{busy?"Salvando...":"Salvar cupom"}</button></div>
  </section>}
  <div className="crz-couponmanager-layout"><section className="crz-couponmanager-list">{visible.map((c:Row)=><button key={c.id} type="button" className={selected?.id===c.id?"is-selected":""} onClick={()=>setSelected(c)}><span><strong>{c.code}</strong><small>{c.origin} • {date(c.expires_at)}</small></span><span><Badge tone={c.active?"green":"neutral"}>{benefit(c)}</Badge><small>{c.real_uses}{c.max_uses?"/"+c.max_uses:""} usos</small></span></button>)}{!visible.length&&<div className="crz-couponmanager-empty">Nenhum cupom.</div>}</section>
  <aside className="crz-couponmanager-detail">{!selected?<div className="crz-couponmanager-empty"><strong>Selecione um cupom</strong></div>:<><header><div><small>{selected.origin.toUpperCase()}</small><h2>{selected.code}</h2><span>{benefit(selected)} • mínimo {selected.min_order_value||0}</span></div><Badge tone={selected.active?"green":"neutral"}>{selected.active?"ATIVO":"OFF"}</Badge></header>
  <div className="crz-couponmanager-grid"><span><small>Usos reais</small><strong>{selected.real_uses}</strong></span><span><small>Máximo</small><strong>{selected.max_uses??"∞"}</strong></span><span><small>Escopo</small><strong>{selected.metadata?.scope_mode==="exclude"?"Todos menos "+(selected.metadata?.excluded_product_ids?.length||0):selected.metadata?.scope_mode==="categories"?(selected.metadata?.category_ids?.length||0)+" categoria(s)":selected.product_ids.length?selected.product_ids.length+" produto(s)":"Todos"}</strong></span><span><small>Clientes</small><strong>{selected.users.length||"Público"}</strong></span></div>
  <div className="crz-couponmanager-actions"><button className="crz-button crz-button--primary crz-button--sm" onClick={()=>openEditor(selected)}>Editar</button><button className="crz-button crz-button--secondary crz-button--sm" onClick={()=>void save({...{id:selected.id,code:selected.code,discountType:selected.discount_type,discountValue:Number(selected.discount_value),minOrderValue:Number(selected.min_order_value||0),maxUses:selected.max_uses==null?"":String(selected.max_uses),origin:selected.origin,active:!selected.active,expiresAt:selected.expires_at?String(selected.expires_at):"",productIds:selected.metadata?.scope_mode==="exclude"?selected.metadata.excluded_product_ids||[]:selected.product_ids,userIds:selected.users.map((u:Row)=>u.user_id),productMode:selected.metadata?.scope_mode==="categories"?"categories":selected.metadata?.scope_mode==="exclude"?"exclude":selected.product_ids.length?"selected":"all",categoryIds:Array.isArray(selected.metadata?.category_ids)?selected.metadata.category_ids:[]}})}>{selected.active?"Desativar":"Ativar"}</button></div>
  </>}</aside></div>
 </div></main>
}
