"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Badge, PageHeader } from "@/core/design-system";
type Row=Record<string,any>;
const money=(c:number)=>"R$ "+((Number(c)||0)/100).toFixed(2);
export function LuckManagerPage(){
 const [data,setData]=useState<any>(null),[state,setState]=useState("loading"),[campaign,setCampaign]=useState<Row|null>(null),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch("/api/admin/luck",{cache:"no-store"});const p=await r.json();if(!r.ok)throw new Error();setData(p);setState("ready")}catch{setState("error")}},[]);
 useEffect(()=>{void load()},[load]);const prizes=useMemo(()=>campaign?data?.prizes?.filter((p:Row)=>p.campaign_id===campaign.id)||[]:[],[campaign,data]);
 const saveCampaign=async(row?:Row)=>{const title=window.prompt("Título:",row?.title||"");if(!title)return;const mode=window.prompt("Modo: wheel, scratch ou drop",row?.mode||"scratch")||"";const cost=window.prompt("Custo por jogada em CRAZZY BONUS (R$):",String(Number(row?.bonus_cost_cents||0)/100));if(cost===null)return;const active=window.confirm(row?.active===false?"Ativar esta campanha?":"Manter campanha ativa? OK = ativa");const r=await fetch("/api/admin/luck",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save_campaign",id:row?.id,title,slug:row?.slug,mode,description:row?.description||"",bonusCostCents:Math.round(Number(cost.replace(",","."))*100),active,sortOrder:row?.sort_order||0})});setNotice(r.ok?"Campanha salva.":"Falha ao salvar.");if(r.ok)await load()};
 const savePrize=async(row?:Row)=>{if(!campaign)return;const label=window.prompt("Nome do prêmio:",row?.label||"CRAZZY BONUS");if(!label)return;const type=window.prompt("Tipo: coupon, bonus, product, reward ou none",row?.prize_type||"bonus")||"";const weight=Number(window.prompt("Peso/chance relativa:",String(row?.weight||10)));const stockRaw=window.prompt("Estoque máximo (vazio = infinito):",row?.stock_limit==null?"":String(row.stock_limit));const body:any={action:"save_prize",id:row?.id,campaignId:campaign.id,label,prizeType:type,weight,active:true,stockLimit:stockRaw?.trim()?Number(stockRaw):null,sortOrder:row?.sort_order||0};if(type==="bonus"){const v=window.prompt("Valor do prêmio em CRAZZY BONUS (R$):",String(Number(row?.config?.bonus_cents||0)/100));body.bonusCents=Math.round(Number(String(v||"0").replace(",","."))*100)}else if(type==="coupon"){body.discountType=window.prompt("percentage ou fixed",row?.config?.discount_type||"percentage");body.discountValue=Number(window.prompt("Valor:",String(row?.config?.discount_value||10)));body.minOrderValue=Number(window.prompt("Pedido mínimo R$:",String(row?.config?.min_order_value||0)));body.expiresHours=Number(window.prompt("Validade em horas:",String(row?.config?.expires_hours||72)))}else if(type==="product"){body.productId=window.prompt("UUID do produto:",row?.config?.product_id||"");body.productPlanId=window.prompt("UUID do plano (opcional):",row?.config?.product_plan_id||"");body.durationMinutes=Number(window.prompt("Duração em minutos (0 = sem expiração):",String(row?.config?.duration_minutes||0)))}else if(type==="reward"){body.note=window.prompt("Descrição da entrega manual:",row?.config?.note||"")||""}const r=await fetch("/api/admin/luck",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setNotice(r.ok?"Prêmio salvo.":"Falha ao salvar prêmio.");if(r.ok)await load()};
 if(state==="loading")return <main className="crz-luckmanager-state"><span className="crz-spinner"/><strong>Carregando Arcade...</strong></main>;if(state==="error"||!data)return <main className="crz-luckmanager-state"><strong>Arcade Manager indisponível.</strong><button onClick={()=>void load()}>Tentar novamente</button></main>;
 return <main className="crz-luckmanager"><div className="crz-container"><PageHeader eyebrow="CRAZZY ARCADE MANAGER" title="Prêmios e custo em CRAZZY BONUS" description="Nenhuma jogada usa PIX direto. O servidor debita o bônus, sorteia, registra e entrega o prêmio." actions={<button className="crz-button crz-button--primary crz-button--sm" onClick={()=>void saveCampaign()}>+ Campanha</button>}/>{notice&&<p className="crz-luckmanager-notice">{notice}</p>}<div className="crz-luckmanager-layout"><section className="crz-luckmanager-campaigns"><header><strong>Campanhas</strong></header>{data.campaigns.map((c:Row)=><button type="button" key={c.id} className={campaign?.id===c.id?"is-selected":""} onClick={()=>setCampaign(c)}><span><strong>{c.title}</strong><small>{c.mode} • {money(c.bonus_cost_cents)} BONUS</small></span><Badge tone={c.active&&c.bonus_cost_cents>0?"green":"neutral"}>{c.active&&c.bonus_cost_cents>0?"ATIVA":"CONFIGURAR"}</Badge><em onClick={e=>{e.stopPropagation();void saveCampaign(c)}}>Editar</em></button>)}</section><aside className="crz-luckmanager-prizes"><header><div><strong>{campaign?.title||"Selecione uma campanha"}</strong><small>{campaign?prizes.length+" prêmios":"—"}</small></div>{campaign&&<button onClick={()=>void savePrize()}>+ Prêmio</button>}</header>{prizes.map((p:Row)=><article key={p.id}><span><strong>{p.label}</strong><small>{p.prize_type} • estoque {p.stock_limit==null?"∞":Math.max(0,p.stock_limit-p.wins_count)+"/"+p.stock_limit}</small></span><span><Badge tone={p.active?"green":"neutral"}>{p.weight} peso</Badge><small>{p.wins_count} vitória(s)</small></span><button onClick={()=>void savePrize(p)}>Editar</button></article>)}</aside></div></div></main>
}
