"use client";
import { NeonIcon, PageHeader } from "@/core/design-system";
import { useAuth } from "@/modules/auth/AuthProvider";
const clubModules=[
 {id:"bonus",title:"FREE • GRÁTIS",description:"Ganhe testes, bônus promocional e benefícios disponíveis para sua conta.",href:"/bonus",icon:"crown" as const,tone:"blue",status:"Carteira promocional"},
 {id:"arcade",title:"PRÊMIOS • ROLETA + RASPADINHA",description:"Gire a roleta, raspe e acompanhe os prêmios do CRAZZY Club.",href:"/club/luck",icon:"lightning" as const,tone:"pink",status:"Raspadinha e minigames"},
 {id:"rewards",title:"REWARDS",description:"Complete missões e resgate recompensas grátis.",href:"/club/rewards",icon:"crown" as const,tone:"blue",status:"Missões e recompensas"},
 {id:"coupons",title:"MEUS CUPONS",description:"Cupons liberados, regras de uso e validade.",href:"/painel/cupons",icon:"featured" as const,tone:"gold",status:"Descontos e prêmios"},
 {id:"rank",title:"CRAZZY RANK",description:"Badges, progressão e destaques da comunidade.",href:"/club/rank",icon:"community" as const,tone:"green",status:"Ranking e badges"},
];
export function ClubHubPage(){const {user,loading}=useAuth();return <main className="crz-club-page"><div className="crz-container"><PageHeader eyebrow="CRAZZY CLUB" title="FREE, prêmios e vantagens" description="Ganhe grátis, gire, raspe, use seus cupons e acompanhe tudo do CRAZZY Club em um só lugar." actions={user?<a className="crz-button crz-button--secondary crz-button--sm" href="/painel">Meu painel</a>:<a className="crz-button crz-button--primary crz-button--sm" href="/login">Entrar no CLUB</a>}/><section className="crz-club-hero-card"><div className="crz-club-hero-card__glow" aria-hidden="true"/><div className="crz-club-hero-card__copy"><span>MEMBRO CRAZZY</span><h2>{loading?"Carregando seu CLUB...":user?"Bem-vindo, "+(user.username||"membro"):"Entre para desbloquear o CLUB"}</h2><p>Compras elegíveis podem gerar CRAZZY BONUS. O saldo é promocional, não sacável e segue as regras exibidas de cada plano.</p></div><div className="crz-club-hero-card__mark"><NeonIcon name="crown" size={82}/></div></section><section className="crz-club-grid" aria-label="Módulos do CRAZZY CLUB">{clubModules.map(m=><a href={m.href} key={m.id} className={"crz-club-card crz-club-card--"+m.tone}><div className="crz-club-card__icon"><NeonIcon name={m.icon} size={38}/></div><div><small>{m.status}</small><h3>{m.title}</h3><p>{m.description}</p></div><span className="crz-club-card__arrow">→</span></a>)}</section><section className="crz-club-security"><NeonIcon name="shield" size={28}/><div><strong>Seu histórico fica organizado</strong><span>Acompanhe bônus, prêmios e resgates direto na sua conta.</span></div></section></div></main>}
